**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [11]:
#Code here
a = np.zeros((10))
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [12]:
#Code here

a = int(input("Enter 1st number "))
b = int(input("Enter 2nd number "))

arr = np.random.random((a,b))
print("array ",arr)
avg = np.average(arr)
print("average of array ",avg)

Enter 1st number 3
Enter 2nd number 4
array  [[0.13518842 0.83756408 0.68266416 0.9158393 ]
 [0.27492485 0.33520107 0.51655591 0.77209972]
 [0.32970547 0.23601444 0.6592555  0.97189238]]
average of array  0.5555754429673163


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [33]:
#Code here
def fun(a,b):
  l = np.ones((a,b))
  l[1:-1,1:-1] = 0
  return l


In [34]:
fun(4,4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [45]:
#Code here
a= np.linspace(0,1,12)
a[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [38]:
#Code here
# identity matrix is square matrix

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [51]:
#Code here
z = np.zeros((5,5),dtype=np.int32)
a = np.arange(5)
z+=a
z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int32)

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [9]:
#code here
import numpy as np
l = np.random.randint(1,101,size=(10,2))
print(l)
p = np.array([2,3])

# def distance(l,p):
#   dis = []
#   for i in l:
#     dis.append(((i[1]-p[1])**2 + (i[0]-p[0]**2))**0.5)
#   return dis

dis =np.sqrt(np.sum((l - p)**2,axis=1))


dis

[[27 15]
 [62 69]
 [13 84]
 [84 96]
 [88 65]
 [24 21]
 [58 56]
 [67 43]
 [19 63]
 [92 77]]


array([ 27.73084925,  89.19641248,  81.74350127, 123.98790264,
       106.01886625,  28.42534081,  77.1038261 ,  76.32168761,
        62.36184731, 116.51609331])

In [4]:
distance(l,p)

[44.05678154382138,
 82.5348411278534,
 31.080540535840107,
 83.50449089719666,
 3.0,
 78.37091297158659,
 74.47818472546173,
 37.5632799419859,
 11.958260743101398,
 3.4641016151377544]

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [14]:
#Code here

shape  =(6,7,8)
ind = 99 #element start from zero

z = ind % shape[2]
y = (ind // shape[2])%shape[1]
x = (ind //(shape[2]*shape[1]))%shape[0]
print(x,y,z)

1 5 3


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [25]:
#Code here
s = input()
l= (s.split())
arr = np.array(l,dtype=np.float32)
arr[::-1]


1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.], dtype=float32)

In [27]:
print(arr)

[  1.   2.   3.   4.  -8. -10.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [31]:
#Code here
print("element_counts",arr.size)


element_counts 6


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [36]:
#Code here
z = np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])
ans = np.exp(z)/np.sum(1+np.exp(z))
ans

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [40]:
#Coder here
a= np.array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]])

b= np.array([[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]])

c= np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
 [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

def stack(*args):
  return np.vstack(args)



In [41]:
stack(a,b,c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [52]:
#code here
arr = np.arange(16).reshape(4,4)
print(arr)
sub = np.mean(arr,axis=1,keepdims=True)
print(sub)
arr - sub

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1.5]
 [ 5.5]
 [ 9.5]
 [13.5]]


array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [58]:
#Code here
arr = np.arange(16).reshape(4,4)
print(arr)
arr[:,[0,1]] = arr[:,[1,0]]
arr

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


###`Q-16:` Replace odd elements in arrays with -1.

In [67]:
#Code here
arr = np.arange(16).reshape(4,4)
arr[arr%2 !=0] = -1
arr

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1],
       [12, -1, 14, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [74]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
if sum(a)>sum(b):
  print("result -->",a)
else:
  print("result -->",b)

result --> [6 3 1 5 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [75]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 272, 1363, 4812, 2040, 6116],
       [ 717, 1116, 8871, 7759, 5842],
       [7186, 3937,   65, 5325,  559],
       [1388, 2182,  386, 3318,  552],
       [5289, 3683,  384, 1754, 9376],
       [4698, 9836,  530, 8100, 9622],
       [ 303, 5428, 5425, 5087,  563],
       [5768,  796, 4246, 8991, 3623]])

In [77]:
#Code here
arr = (arr1 - np.min(arr1))/(np.max(arr1) - np.min(arr1))
arr

array([[0.02118514, 0.13284208, 0.4858254 , 0.20212875, 0.61928155],
       [0.06672807, 0.1075632 , 0.90123836, 0.7874322 , 0.59123938],
       [0.72878927, 0.39627469, 0.        , 0.5383277 , 0.05055777],
       [0.13540068, 0.21666155, 0.03285232, 0.33292396, 0.04984137],
       [0.53464333, 0.3702794 , 0.03264763, 0.17285846, 0.95292191],
       [0.47415822, 1.        , 0.04758981, 0.82233139, 0.97809845],
       [0.02435779, 0.5488691 , 0.54856207, 0.51396991, 0.05096715],
       [0.58366595, 0.07481322, 0.42789888, 0.9135196 , 0.36413878]])

In [79]:
np.max(arr1)

9836

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [97]:
#Code here
arr=np.array([12,34,40,7,1,0])

def n_max(arr,ind):
  arr =sorted(arr,reverse=True)
  return arr[ind-1]

In [98]:
n_max(arr,3)

12

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [103]:
#code here
a = np.array([1,2,3])
x = np.repeat(a,3)
y = np.tile(a,3)
np.concatenate((x,y))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [101]:
y

array([1, 2, 3, 1, 2, 3, 1, 2, 3])